contact_links:
  - name: Discussions and support
    url: https://github.com/sn4k3/Updatum/discussions
    about: Questions, suggestions, ideas, tutorials, show and tell and general talk

blank_issues_enabled: false
